---
user: 
  name: hunter

packages:
  install:
    - git
    - vscode
    - python36
    - python36-pip
    - vim
    - discord
    - firefox
    - dashlane
    
  remove:
    - nano

vscode:
  extensions:
    - gitlens
    - python
    - yaml
    - remote ssh